# TASK1

1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [14]:
import sys
try:
    num = int(input("enter the number:"))
    print(5/num)
except:
    print("The value of num cannot be 0", sys.exc_info()[0])
finally:
    print("finally done")

enter the number:0
The value of num cannot be 0 <class 'ZeroDivisionError'>
finally done


2.Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [15]:
subjects=["Americans","Indians"]
verbs=[" play "," watch "]
objects=["Baseball","Cricket"]
for sub in subjects:
    for verb in verbs:
        for obj in objects:
             print(sub+verb+obj)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [16]:
result = [sub+verb+obj for sub in subjects for verb in verbs for obj in objects]
result

['Americans play Baseball',
 'Americans play Cricket',
 'Americans watch Baseball',
 'Americans watch Cricket',
 'Indians play Baseball',
 'Indians play Cricket',
 'Indians watch Baseball',
 'Indians watch Cricket']

# TASK 2

1.Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [17]:
import numpy as np
x = np.array([1, 2, 3, 5])
array1 = np.vander(x, increasing = False)
array1

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [18]:
x = np.array([1, 2, 3, 5])
N=4
array2 = np.column_stack([x**(N-1-i) for i in range(N)])
array2

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]], dtype=int32)

In [19]:
array3 = np.vander(x, N)
array3

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [20]:
array4 = np.vander(x, increasing=True)
array4

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])